### ISSUE TITLE
Can't analyze the issue please help asap

### ISSUE THREAD

**Issue by MuddassirPasta** [Vinelab/NeoEloquent#203]
Fatal error: Uncaught ReflectionException: Class db does not exist in C:\xampp\htdocs\FYP\vendor\laravel\framework\src\Illuminate\Container\Container.php:749 Stack trace: #0 C:\xampp\htdocs\FYP\vendor\laravel\framework\src\Illuminate\Container\Container.php(749): ReflectionClass->__construct('db') #1 C:\xampp\htdocs\FYP\vendor\laravel\framework\src\Illuminate\Container\Container.php(644): Illuminate\Container\Container->build('db', Array) #2 C:\xampp\htdocs\FYP\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(709): Illuminate\Container\Container->make('db', Array) #3 C:\xampp\htdocs\FYP\vendor\laravel\framework\src\Illuminate\Container\Container.php(1203): Illuminate\Foundation\Application->make('db') #4 C:\xampp\htdocs\FYP\vendor\vinelab\neoeloquent\src\Vinelab\NeoEloquent\NeoEloquentServiceProvider.php(44): Illuminate\Container\Container->offsetGet('db') #5 C:\xampp\htdocs\FYP\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(565): Vinelab\NeoEloquent\NeoEloquentServiceProvider->regist in C:\xampp\htdocs\FYP\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 749

**Comment by MuddassirPasta** [comment]
<?php

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| The first thing we will do is create a new Laravel application instance
| which serves as the "glue" for all the components of Laravel, and is
| the IoC container for the system binding all of the various parts.
|
*/

$app = new Illuminate\Foundation\Application(
    realpath(__DIR__.'/../')
);

/*
|--------------------------------------------------------------------------
| Bind Important Interfaces
|--------------------------------------------------------------------------
|
| Next, we need to bind some important interfaces into the container so
| we will be able to resolve them when needed. The kernels serve the
| incoming requests to this application from both the web and CLI.
|
*/


$app->singleton(
    Illuminate\Contracts\Http\Kernel::class,
    App\Http\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

$app->register(
    Vinelab\NeoEloquent\NeoEloquentServiceProvider::class
);


/*
|--------------------------------------------------------------------------
| Return The Application
|--------------------------------------------------------------------------
|
| This script returns the application instance. The instance is given to
| the calling script so we can separate the building of the instances
| from the actual running of the application and sending responses.
|
*/

return $app;
