### ISSUE TITLE
exception in neo4j v 3.2

### ISSUE THREAD

**Issue by AzeemMichael** [Vinelab/NeoEloquent#232]
getting error when using neo4j v 3.2

```[Everyman\Neo4j\Exception]
  Unable to execute query [400]:
  Headers: Array
  (
      [Date] =>  Thu, 11 May 2017 23:47:21 GMT
      [Content-Type] =>  application/json; charset=UTF-8; strea
  m=true
      [Access-Control-Allow-Origin] =>  *
      [Content-Length] =>  22270
      [Server] =>  Jetty(9.2.9.v20150224)
  )
  Body: Array
  (
      [message] => Internal error - should have used fall back
  to execute query, but something went horribly wrong
      [exception] => CantHandleQueryException
      [fullname] => org.neo4j.cypher.internal.ir.v3_2.exception
  .CantHandleQueryException
      [stackTrace] => Array
          (
              [0] => org.neo4j.cypher.internal.compiler.v3_2.as
  t.convert.plannerQuery.ClauseConverters$$anonfun$addStartToLo
  gicalPlanInput$1.apply(ClauseConverters.scala:471)
              [1] => org.neo4j.cypher.internal.compiler.v3_2.as
  t.convert.plannerQuery.ClauseConverters$$anonfun$addStartToLo
  gicalPlanInput$1.apply(ClauseConverters.scala:460)
              [2] => org.neo4j.cypher.internal.ir.v3_2.PlannerQ
  uery$class.amendQueryGraph(PlannerQuery.scala:66)
              [3] => org.neo4j.cypher.internal.ir.v3_2.RegularP
  lannerQuery.amendQueryGraph(PlannerQuery.scala:179)
              [4] => org.neo4j.cypher.internal.compiler.v3_2.as
  t.convert.plannerQuery.PlannerQueryBuilder$$anonfun$amendQuer
  yGraph$1.apply(PlannerQueryBuilder.scala:34)
              [5] => org.neo4j.cypher.internal.compiler.v3_2.as
  t.convert.plannerQuery.PlannerQueryBuilder$$anonfun$amendQuer
  yGraph$1.apply(PlannerQueryBuilder.scala:34)
              [6] => org.neo4j.cypher.internal.ir.v3_2.PlannerQ
  uery$class.updateTailOrSelf(PlannerQuery.scala:81)
              [7] => org.neo4j.cypher.internal.ir.v3_2.RegularP
  lannerQuery.updateTailOrSelf(PlannerQuery.scala:179)
              [8] => org.neo4j.cypher.internal.compiler.v3_2.as
  t.convert.plannerQuery.PlannerQueryBuilder.amendQueryGraph(Pl
  annerQueryBuilder.scala:34)
              [9] => org.neo4j.cypher.internal.compiler.v3_2.as
  t.convert.plannerQuery.ClauseConverters$.addStartToLogicalPla
  nInput(ClauseConverters.scala:460)
              [10] => org.neo4j.cypher.internal.compiler.v3_2.a
  st.convert.plannerQuery.ClauseConverters$.addToLogicalPlanInp
  ut(ClauseConverters.scala:41)
              [11] => org.neo4j.cypher.internal.compiler.v3_2.a
  st.convert.plannerQuery.StatementConverters$$anonfun$toPlanne
  rQueryBuilder$1.apply(StatementConverters.scala:34)
              [12] => org.neo4j.cypher.internal.compiler.v3_2.a
  st.convert.plannerQuery.StatementConverters$$anonfun$toPlanne
  rQueryBuilder$1.apply(StatementConverters.scala:33)
              [13] => scala.collection.LinearSeqOptimized$class
  .foldLeft(LinearSeqOptimized.scala:124)
              [14] => scala.collection.immutable.List.foldLeft(
  List.scala:84)
              [15] => org.neo4j.cypher.internal.compiler.v3_2.a
  st.convert.plannerQuery.StatementConverters$.toPlannerQueryBu
  ilder(StatementConverters.scala:33)
              [16] => org.neo4j.cypher.internal.compiler.v3_2.a
  st.convert.plannerQuery.StatementConverters$.toUnionQuery(Sta
  tementConverters.scala:58)
              [17] => org.neo4j.cypher.internal.compiler.v3_2.p
  hases.CreatePlannerQuery$.process(CreatePlannerQuery.scala:38
  )
              [18] => org.neo4j.cypher.internal.compiler.v3_2.p
  hases.CreatePlannerQuery$.process(CreatePlannerQuery.scala:29
  )
              [19] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.Phase$$anonfun$transform$1.apply(Phase.scala:39)
              [20] => org.neo4j.cypher.internal.frontend.v3_2.h
  elpers.package$$anonfun$closing$1.apply(package.scala:27)
              [21] => org.neo4j.cypher.internal.frontend.v3_2.h
  elpers.package$$anonfun$closing$1.apply(package.scala:27)
              [22] => org.neo4j.cypher.internal.frontend.v3_2.h
  elpers.package$.using(package.scala:35)
              [23] => org.neo4j.cypher.internal.frontend.v3_2.h
  elpers.package$.closing(package.scala:27)
              [24] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.Phase$class.transform(Phase.scala:38)
              [25] => org.neo4j.cypher.internal.compiler.v3_2.p
  hases.CreatePlannerQuery$.transform(CreatePlannerQuery.scala:
  29)
              [26] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.PipeLine.transform(Transformer.scala:48)
              [27] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.PipeLine.transform(Transformer.scala:52)
              [28] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.PipeLine.transform(Transformer.scala:48)
              [29] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.PipeLine.transform(Transformer.scala:52)
              [30] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.PipeLine.transform(Transformer.scala:48)
              [31] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.PipeLine.transform(Transformer.scala:48)
              [32] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.If.transform(Transformer.scala:83)
              [33] => org.neo4j.cypher.internal.frontend.v3_2.p
  hases.PipeLine.transform(Transformer.scala:52)
              [34] => org.neo4j.cypher.internal.compiler.v3_2.C
  ypherCompiler.org$neo4j$cypher$internal$compiler$v3_2$CypherC
  ompiler$$createPlan$1(CypherCompiler.scala:80)
              [35] => org.neo4j.cypher.internal.compiler.v3_2.C
  ypherCompiler$$anonfun$2.apply(CypherCompiler.scala:85)
              [36] => org.neo4j.cypher.internal.compiler.v3_2.C
  ypherCompiler$$anonfun$2.apply(CypherCompiler.scala:85)
              [37] => org.neo4j.cypher.internal.compiler.v3_2.Q
  ueryCache$$anonfun$getOrElseUpdate$1$$anonfun$apply$1.apply(C
  acheAccessor.scala:36)
              [38] => org.neo4j.cypher.internal.compiler.v3_2.M
  onitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:5
  7)
              [39] => org.neo4j.cypher.internal.compiler.v3_2.L
  FUCache$$anon$1.apply(LFUCache.scala:31)
              [40] => com.github.benmanes.caffeine.cache.Bounde
  dLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.jav
  a:1973)
              [41] => java.util.concurrent.ConcurrentHashMap.co
  mpute(ConcurrentHashMap.java:1853)
              [42] => com.github.benmanes.caffeine.cache.Bounde
  dLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
              [43] => com.github.benmanes.caffeine.cache.Bounde
  dLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
              [44] => com.github.benmanes.caffeine.cache.LocalC
  ache.computeIfAbsent(LocalCache.java:113)
              [45] => com.github.benmanes.caffeine.cache.LocalM
  anualCache.get(LocalManualCache.java:54)
              [46] => org.neo4j.cypher.internal.compiler.v3_2.L
  FUCache.getOrElseUpdate(LFUCache.scala:30)
              [47] => org.neo4j.cypher.internal.compiler.v3_2.L
  FUCache.apply(LFUCache.scala:48)
              [48] => org.neo4j.cypher.internal.compiler.v3_2.M
  onitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:55
  )
              [49] => org.neo4j.cypher.internal.compiler.v3_2.Q
  ueryCache$$anonfun$getOrElseUpdate$1.apply(CacheAccessor.scal
  a:34)
              [50] => scala.collection.Iterator$$anon$9.next(It
  erator.scala:162)
              [51] => scala.collection.Iterator$$anon$12.nextCu
  r(Iterator.scala:434)
              [52] => scala.collection.Iterator$$anon$12.hasNex
  t(Iterator.scala:440)
              [53] => scala.collection.Iterator$$anon$12.next(I
  terator.scala:444)
              [54] => org.neo4j.cypher.internal.compiler.v3_2.Q
  ueryCache.getOrElseUpdate(CacheAccessor.scala:46)
              [55] => org.neo4j.cypher.internal.compiler.v3_2.C
  ypherCompiler.planPreparedQuery(CypherCompiler.scala:85)
              [56] => org.neo4j.cypher.internal.compatibility.v
  3_2.Compatibility$$anon$1$$anonfun$plan$1.apply(Compatibility
  .scala:72)
              [57] => org.neo4j.cypher.internal.compatibility.v
  3_2.Compatibility$$anon$1$$anonfun$plan$1.apply(Compatibility
  .scala:69)
              [58] => org.neo4j.cypher.internal.compatibility.v
  3_2.exceptionHandler$runSafely$.apply(exceptionHandler.scala:
  90)
              [59] => org.neo4j.cypher.internal.compatibility.v
  3_2.Compatibility$$anon$1.plan(Compatibility.scala:69)
              [60] => org.neo4j.cypher.internal.ExecutionEngine
  .org$neo4j$cypher$internal$ExecutionEngine$$producePlan$1(Exe
  cutionEngine.scala:167)
              [61] => org.neo4j.cypher.internal.ExecutionEngine
  $$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:170)
              [62] => org.neo4j.cypher.internal.ExecutionEngine
  $$anonfun$liftedTree1$1$1.apply(ExecutionEngine.scala:170)
              [63] => org.neo4j.cypher.internal.compiler.v3_2.Q
  ueryCache$$anonfun$getOrElseUpdate$1$$anonfun$apply$1.apply(C
  acheAccessor.scala:36)
              [64] => org.neo4j.cypher.internal.compiler.v3_2.M
  onitoringCacheAccessor$$anonfun$1.apply(CacheAccessor.scala:5
  7)
              [65] => org.neo4j.cypher.internal.compiler.v3_2.L
  FUCache$$anon$1.apply(LFUCache.scala:31)
              [66] => com.github.benmanes.caffeine.cache.Bounde
  dLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.jav
  a:1973)
              [67] => java.util.concurrent.ConcurrentHashMap.co
  mpute(ConcurrentHashMap.java:1853)
              [68] => com.github.benmanes.caffeine.cache.Bounde
  dLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
              [69] => com.github.benmanes.caffeine.cache.Bounde
  dLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
              [70] => com.github.benmanes.caffeine.cache.LocalC
  ache.computeIfAbsent(LocalCache.java:113)
              [71] => com.github.benmanes.caffeine.cache.LocalM
  anualCache.get(LocalManualCache.java:54)
              [72] => org.neo4j.cypher.internal.compiler.v3_2.L
  FUCache.getOrElseUpdate(LFUCache.scala:30)
              [73] => org.neo4j.cypher.internal.compiler.v3_2.L
  FUCache.apply(LFUCache.scala:48)
              [74] => org.neo4j.cypher.internal.compiler.v3_2.M
  onitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:55
  )
              [75] => org.neo4j.cypher.internal.compiler.v3_2.Q
  ueryCache$$anonfun$getOrElseUpdate$1.apply(CacheAccessor.scal
  a:34)
              [76] => scala.collection.Iterator$$anon$9.next(It
  erator.scala:162)
              [77] => scala.collection.Iterator$$anon$12.nextCu
  r(Iterator.scala:434)
              [78] => scala.collection.Iterator$$anon$12.hasNex
  t(Iterator.scala:440)
              [79] => scala.collection.Iterator$$anon$12.next(I
  terator.scala:444)
              [80] => org.neo4j.cypher.internal.compiler.v3_2.Q
  ueryCache.getOrElseUpdate(CacheAccessor.scala:46)
              [81] => org.neo4j.cypher.internal.ExecutionEngine
  .liftedTree1$1(ExecutionEngine.scala:170)
              [82] => org.neo4j.cypher.internal.ExecutionEngine
  .planQuery(ExecutionEngine.scala:156)
              [83] => org.neo4j.cypher.internal.ExecutionEngine
  .execute(ExecutionEngine.scala:106)
              [84] => org.neo4j.cypher.internal.javacompat.Exec
  utionEngine.executeQuery(ExecutionEngine.java:61)
              [85] => org.neo4j.server.rest.web.CypherService.c
  ypher(CypherService.java:131)
              [86] => java.lang.reflect.Method.invoke(Method.ja
  va:498)
              [87] => org.neo4j.server.rest.transactional.Trans
  actionalRequestDispatcher.dispatch(TransactionalRequestDispat
  cher.java:147)
              [88] => org.neo4j.server.rest.dbms.AuthorizationE
  nabledFilter.doFilter(AuthorizationEnabledFilter.java:122)
              [89] => org.neo4j.server.rest.web.CollectUserAgen
  tFilter.doFilter(CollectUserAgentFilter.java:69)
              [90] => java.lang.Thread.run(Thread.java:745)
          )
      [errors] => Array
          (
              [0] => Array
                  (
                      [code] => Neo.DatabaseError.General.Unkno
  wnError
                      [message] => Internal error - should have
   used fall back to execute query, but something went horribly
   wrong
                      [stackTrace] => org.neo4j.cypher.internal
  .ir.v3_2.exception.CantHandleQueryException: Internal error -
   should have used fall back to execute query, but something w
  ent horribly wrong
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.ClauseConverters$$anonfun$addStartToLogicalPlanInput$
  1.apply(ClauseConverters.scala:471)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.ClauseConverters$$anonfun$addStartToLogicalPlanInput$
  1.apply(ClauseConverters.scala:460)
  	at org.neo4j.cypher.internal.ir.v3_2.PlannerQuery$class.amen
  dQueryGraph(PlannerQuery.scala:66)
  	at org.neo4j.cypher.internal.ir.v3_2.RegularPlannerQuery.ame
  ndQueryGraph(PlannerQuery.scala:179)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.PlannerQueryBuilder$$anonfun$amendQueryGraph$1.apply(
  PlannerQueryBuilder.scala:34)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.PlannerQueryBuilder$$anonfun$amendQueryGraph$1.apply(
  PlannerQueryBuilder.scala:34)
  	at org.neo4j.cypher.internal.ir.v3_2.PlannerQuery$class.upda
  teTailOrSelf(PlannerQuery.scala:81)
  	at org.neo4j.cypher.internal.ir.v3_2.RegularPlannerQuery.upd
  ateTailOrSelf(PlannerQuery.scala:179)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.PlannerQueryBuilder.amendQueryGraph(PlannerQueryBuild
  er.scala:34)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.ClauseConverters$.addStartToLogicalPlanInput(ClauseCo
  nverters.scala:460)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.ClauseConverters$.addToLogicalPlanInput(ClauseConvert
  ers.scala:41)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.StatementConverters$$anonfun$toPlannerQueryBuilder$1.
  apply(StatementConverters.scala:34)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.StatementConverters$$anonfun$toPlannerQueryBuilder$1.
  apply(StatementConverters.scala:33)
  	at scala.collection.LinearSeqOptimized$class.foldLeft(Linear
  SeqOptimized.scala:124)
  	at scala.collection.immutable.List.foldLeft(List.scala:84)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.StatementConverters$.toPlannerQueryBuilder(StatementC
  onverters.scala:33)
  	at org.neo4j.cypher.internal.compiler.v3_2.ast.convert.plann
  erQuery.StatementConverters$.toUnionQuery(StatementConverters
  .scala:58)
  	at org.neo4j.cypher.internal.compiler.v3_2.phases.CreatePlan
  nerQuery$.process(CreatePlannerQuery.scala:38)
  	at org.neo4j.cypher.internal.compiler.v3_2.phases.CreatePlan
  nerQuery$.process(CreatePlannerQuery.scala:29)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.Phase$$ano
  nfun$transform$1.apply(Phase.scala:39)
  	at org.neo4j.cypher.internal.frontend.v3_2.helpers.package$$
  anonfun$closing$1.apply(package.scala:27)
  	at org.neo4j.cypher.internal.frontend.v3_2.helpers.package$$
  anonfun$closing$1.apply(package.scala:27)
  	at org.neo4j.cypher.internal.frontend.v3_2.helpers.package$.
  using(package.scala:35)
  	at org.neo4j.cypher.internal.frontend.v3_2.helpers.package$.
  closing(package.scala:27)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.Phase$clas
  s.transform(Phase.scala:38)
  	at org.neo4j.cypher.internal.compiler.v3_2.phases.CreatePlan
  nerQuery$.transform(CreatePlannerQuery.scala:29)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.t
  ransform(Transformer.scala:48)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.t
  ransform(Transformer.scala:52)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.t
  ransform(Transformer.scala:48)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.t
  ransform(Transformer.scala:52)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.t
  ransform(Transformer.scala:48)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.t
  ransform(Transformer.scala:48)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.If.transfo
  rm(Transformer.scala:83)
  	at org.neo4j.cypher.internal.frontend.v3_2.phases.PipeLine.t
  ransform(Transformer.scala:52)
  	at org.neo4j.cypher.internal.compiler.v3_2.CypherCompiler.or
  g$neo4j$cypher$internal$compiler$v3_2$CypherCompiler$$createP
  lan$1(CypherCompiler.scala:80)
  	at org.neo4j.cypher.internal.compiler.v3_2.CypherCompiler$$a
  nonfun$2.apply(CypherCompiler.scala:85)
  	at org.neo4j.cypher.internal.compiler.v3_2.CypherCompiler$$a
  nonfun$2.apply(CypherCompiler.scala:85)
  	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache$$anonf
  un$getOrElseUpdate$1$$anonfun$apply$1.apply(CacheAccessor.sca
  la:36)
  	at org.neo4j.cypher.internal.compiler.v3_2.MonitoringCacheAc
  cessor$$anonfun$1.apply(CacheAccessor.scala:57)
  	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache$$anon$1.
  apply(LFUCache.scala:31)
  	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lamb
  da$doComputeIfAbsent$16(BoundedLocalCache.java:1973)
  	at java.util.concurrent.ConcurrentHashMap.compute(Concurrent
  HashMap.java:1853)
  	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doCo
  mputeIfAbsent(BoundedLocalCache.java:1971)
  	at com.github.benmanes.caffeine.cache.BoundedLocalCache.comp
  uteIfAbsent(BoundedLocalCache.java:1954)
  	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAb
  sent(LocalCache.java:113)
  	at com.github.benmanes.caffeine.cache.LocalManualCache.get(L
  ocalManualCache.java:54)
  	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache.getOrEls
  eUpdate(LFUCache.scala:30)
  	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache.apply(LF
  UCache.scala:48)
  	at org.neo4j.cypher.internal.compiler.v3_2.MonitoringCacheAc
  cessor.getOrElseUpdate(CacheAccessor.scala:55)
  	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache$$anonf
  un$getOrElseUpdate$1.apply(CacheAccessor.scala:34)
  	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162
  )
  	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala
  :434)
  	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala
  :440)
  	at scala.collection.Iterator$$anon$12.next(Iterator.scala:44
  4)
  	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache.getOrE
  lseUpdate(CacheAccessor.scala:46)
  	at org.neo4j.cypher.internal.compiler.v3_2.CypherCompiler.pl
  anPreparedQuery(CypherCompiler.scala:85)
  	at org.neo4j.cypher.internal.compatibility.v3_2.Compatibilit
  y$$anon$1$$anonfun$plan$1.apply(Compatibility.scala:72)
  	at org.neo4j.cypher.internal.compatibility.v3_2.Compatibilit
  y$$anon$1$$anonfun$plan$1.apply(Compatibility.scala:69)
  	at org.neo4j.cypher.internal.compatibility.v3_2.exceptionHan
  dler$runSafely$.apply(exceptionHandler.scala:90)
  	at org.neo4j.cypher.internal.compatibility.v3_2.Compatibilit
  y$$anon$1.plan(Compatibility.scala:69)
  	at org.neo4j.cypher.internal.ExecutionEngine.org$neo4j$cyphe
  r$internal$ExecutionEngine$$producePlan$1(ExecutionEngine.sca
  la:167)
  	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$lifted
  Tree1$1$1.apply(ExecutionEngine.scala:170)
  	at org.neo4j.cypher.internal.ExecutionEngine$$anonfun$lifted
  Tree1$1$1.apply(ExecutionEngine.scala:170)
  	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache$$anonf
  un$getOrElseUpdate$1$$anonfun$apply$1.apply(CacheAccessor.sca
  la:36)
  	at org.neo4j.cypher.internal.compiler.v3_2.MonitoringCacheAc
  cessor$$anonfun$1.apply(CacheAccessor.scala:57)
  	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache$$anon$1.
  apply(LFUCache.scala:31)
  	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lamb
  da$doComputeIfAbsent$16(BoundedLocalCache.java:1973)
  	at java.util.concurrent.ConcurrentHashMap.compute(Concurrent
  HashMap.java:1853)
  	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doCo
  mputeIfAbsent(BoundedLocalCache.java:1971)
  	at com.github.benmanes.caffeine.cache.BoundedLocalCache.comp
  uteIfAbsent(BoundedLocalCache.java:1954)
  	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAb
  sent(LocalCache.java:113)
  	at com.github.benmanes.caffeine.cache.LocalManualCache.get(L
  ocalManualCache.java:54)
  	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache.getOrEls
  eUpdate(LFUCache.scala:30)
  	at org.neo4j.cypher.internal.compiler.v3_2.LFUCache.apply(LF
  UCache.scala:48)
  	at org.neo4j.cypher.internal.compiler.v3_2.MonitoringCacheAc
  cessor.getOrElseUpdate(CacheAccessor.scala:55)
  	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache$$anonf
  un$getOrElseUpdate$1.apply(CacheAccessor.scala:34)
  	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162
  )
  	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala
  :434)
  	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala
  :440)
  	at scala.collection.Iterator$$anon$12.next(Iterator.scala:44
  4)
  	at org.neo4j.cypher.internal.compiler.v3_2.QueryCache.getOrE
  lseUpdate(CacheAccessor.scala:46)
  	at org.neo4j.cypher.internal.ExecutionEngine.liftedTree1$1(E
  xecutionEngine.scala:170)
  	at org.neo4j.cypher.internal.ExecutionEngine.planQuery(Execu
  tionEngine.scala:156)
  	at org.neo4j.cypher.internal.ExecutionEngine.execute(Executi
  onEngine.scala:106)
  	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.exec
  uteQuery(ExecutionEngine.java:61)
  	at org.neo4j.server.rest.web.CypherService.cypher(CypherServ
  ice.java:131)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Metho
  d)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodA
  ccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Delegatin
  gMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.i
  nvoke(JavaMethodInvokerFactory.java:60)
  	at com.sun.jersey.server.impl.model.method.dispatch.Abstract
  ResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(A
  bstractResourceMethodDispatchProvider.java:205)
  	at com.sun.jersey.server.impl.model.method.dispatch.Resource
  JavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.ja
  va:75)
  	at org.neo4j.server.rest.transactional.TransactionalRequestD
  ispatcher.dispatch(TransactionalRequestDispatcher.java:147)
  	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accep
  t(HttpMethodRule.java:302)
  	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.ac
  cept(ResourceClassRule.java:108)
  	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.ac
  cept(RightHandPathRule.java:147)
  	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesR
  ule.accept(RootResourceClassesRule.java:84)
  	at com.sun.jersey.server.impl.application.WebApplicationImpl
  ._handleRequest(WebApplicationImpl.java:1542)
  	at com.sun.jersey.server.impl.application.WebApplicationImpl
  ._handleRequest(WebApplicationImpl.java:1473)
  	at com.sun.jersey.server.impl.application.WebApplicationImpl
  .handleRequest(WebApplicationImpl.java:1419)
  	at com.sun.jersey.server.impl.application.WebApplicationImpl
  .handleRequest(WebApplicationImpl.java:1409)
  	at com.sun.jersey.spi.container.servlet.WebComponent.service
  (WebComponent.java:409)
  	at com.sun.jersey.spi.container.servlet.ServletContainer.ser
  vice(ServletContainer.java:558)
  	at com.sun.jersey.spi.container.servlet.ServletContainer.ser
  vice(ServletContainer.java:733)
  	at javax.servlet.http.HttpServlet.service(HttpServlet.java:7
  90)
  	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHol
  der.java:808)
  	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFi
  lter(ServletHandler.java:1669)
  	at org.neo4j.server.rest.dbms.AuthorizationEnabledFilter.doF
  ilter(AuthorizationEnabledFilter.java:122)
  	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFi
  lter(ServletHandler.java:1652)
  	at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter
  (CollectUserAgentFilter.java:69)
  	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFi
  lter(ServletHandler.java:1652)
  	at org.eclipse.jetty.servlet.ServletHandler.doHandle(Servlet
  Handler.java:585)
  	at org.eclipse.jetty.server.session.SessionHandler.doHandle(
  SessionHandler.java:221)
  	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(
  ContextHandler.java:1127)
  	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletH
  andler.java:515)
  	at org.eclipse.jetty.server.session.SessionHandler.doScope(S
  essionHandler.java:185)
  	at org.eclipse.jetty.server.handler.ContextHandler.doScope(C
  ontextHandler.java:1061)
  	at org.eclipse.jetty.server.handler.ScopedHandler.handle(Sco
  pedHandler.java:141)
  	at org.eclipse.jetty.server.handler.HandlerList.handle(Handl
  erList.java:52)
  	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(Ha
  ndlerWrapper.java:97)
  	at org.eclipse.jetty.server.Server.handle(Server.java:497)
  	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.j
  ava:310)
  	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpCo
  nnection.java:257)
  	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractCon
  nection.java:540)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Que
  uedThreadPool.java:635)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(Queu
  edThreadPool.java:555)
  	at java.lang.Thread.run(Thread.java:745)
                  )
          )
  )```

**Comment by IH4xx3R** [comment]
I get the same error :/ Can anyone help ?

**Comment by Mulkave** [comment]
can you please provide more details about the issue? like the code that is generating this?
