### ISSUE TITLE
Composer update failing with Laravel 5.3 and 5.4, using 1.4.* and dev-laravel5.4

### ISSUE THREAD

**Issue by bryanchapel** [Vinelab/NeoEloquent#243]
I'm not sure what I'm doing wrong here or if there's an issue with the readme. When I install Laravel 5.4 and try the readme's install instructions for 5.4 using the require for "vinelab/neoeloquent": "dev-laravel5.4", I get:
`Problem 1
    - The requested package vinelab/neoeloquent dev-laravel5.4 exists as vinelab/neoeloquent[0.1.0, 0.1.1, 0.2.0, 1.2.x-dev, 1.3.1, 1.3.x-dev, 1.4.x-dev, dev-1.5-dev, dev-2.0.0-alpha, dev-2.0.0-alpha-plus, dev-master, v0.3.0, v0.4.0, v1.0.0, v1.0.0-rc.1, v1.0.0-rc.2, v1.0.0-rc.3, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.1.0, v1.1.1, v1.2.0, v1.2.1, v1.2.10, v1.2.11, v1.2.12, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.2.7, v1.2.8, v1.2.9, v1.3.0, v1.3.2, v1.4.0, v1.4.1, v1.4.2, v1.4.3] but these are rejected by your constraint.`

If I try and use neoeloquent 1.4*, with either 5.3 or 5.4 Laravel, I get: 
`PHP Fatal error:  Uncaught ReflectionException: Class db does not exist in /Library/WebServer/Documents/neotest/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
Stack trace:
#0 /Library/WebServer/Documents/neotest/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('db')
#1 /Library/WebServer/Documents/neotest/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('db')
#2 /Library/WebServer/Documents/neotest/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('db')
#3 /Library/WebServer/Documents/neotest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('db')
#4 /Library/WebServer/Documents/neotest/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\Foundation\Application->make('db')
#5 /Library/WebServer/Documents/neotest/vendor/vinelab/neoeloquent/src/Vinelab/Ne in /Library/WebServer/Documents/neotest/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
Script php artisan optimize handling the post-update-cmd event returned with error code 255`

Any suggestions on how to fix any of this?

**Comment by bryanchapel** [comment]
I think I figured it out... Doing anything in the Lumen section of the readme broke everything, and 'Vinelab\NeoEloquent\NeoEloquentServiceProvider' needed to be Vinelab\NeoEloquent\NeoEloquentServiceProvider::class in the providers array. We might want to rewrite the top configuration part of the readme to help troubleshoot some possibly common issues people might have.

I finally got this working with Laravel 5.3 and neoeloquent 1.4.*.
