### ISSUE TITLE
Setting $touches property causes QueryException

### ISSUE THREAD

**Issue by jasekiw** [Vinelab/NeoEloquent#265]
### What is supposed to happen?

It is supposed to change the updated_at on the related model.

### What actually happens: 

It crashes with a query exception

```
Vinelab\NeoEloquent\QueryException: SyntaxException: Invalid input 'H': expected 'i/I' (line 1, column 3 (offset: 2))
"WHERE id(projectPage) = {idprojectPage} and projectPage.deleted_at is null SET projectPage.updated_at = {updated_at_update} RETURN count(projectPage)"
   ^ in C:\projects\work\cstat-backend\vendor\vinelab\neoeloquent\src\Vinelab\NeoEloquent\Connection.php:455
Stack trace:
#0 C:\projects\work\cstat-backend\vendor\vinelab\neoeloquent\src\Vinelab\NeoEloquent\Connection.php(211): Vinelab\NeoEloquent\Connection->run(' WHERE id(proje...', Array, Object(Closure))
#1 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Database\Connection.php(447): Vinelab\NeoEloquent\Connection->affectingStatement(' WHERE id(proje...', Array)
#2 C:\projects\work\cstat-backend\vendor\vinelab\neoeloquent\src\Vinelab\NeoEloquent\Query\Builder.php(148): Illuminate\Database\Connection->update(' WHERE id(proje...', Array)
#3 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(543): Vinelab\NeoEloquent\Query\Builder->update(Array)
#4 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\Relation.php(136): Illuminate\Database\Eloquent\Builder->update(Array)
#5 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\Relation.php(125): Illuminate\Database\Eloquent\Relations\Relation->rawUpdate(Array)
#6 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1622): Illuminate\Database\Eloquent\Relations\Relation->touch()
#7 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1509): Illuminate\Database\Eloquent\Model->touchOwners()
#8 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1475): Illuminate\Database\Eloquent\Model->finishSave(Array)
#9 C:\projects\work\cstat-backend\app\Http\Controllers\ProjectController.php(84): Illuminate\Database\Eloquent\Model->save()
#10 C:\projects\work\cstat-backend\app\Http\Controllers\ProjectController.php(220): App\Http\Controllers\ProjectController->createAndSavePages(Array, Object(App\Models\ProjectForm))
#11 [internal function]: App\Http\Controllers\ProjectController->update(Object(Illuminate\Http\Request), '2394')
#12 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#13 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('update', Array)
#14 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\ProjectController), 'update')
#15 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Route.php(144): Illuminate\Routing\Route->runController()
#16 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#23 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#27 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#28 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#29 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#30 C:\projects\work\cstat-backend\app\Http\Middleware\EnableCors.php(39): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): App\Http\Middleware\EnableCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#38 C:\projects\work\cstat-backend\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#39 C:\projects\work\cstat-backend\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#40 {main}

```

### Steps to reproduce

Follow the documentation and apply this with example models.
https://laravel.com/docs/5.4/eloquent-relationships#touching-parent-timestamps

### Other notes

It seems it is only adding the where statement without a match which is causing this exception.

**Comment by belt-basya** [comment]
I am facing a similar issue. Any solution for this? @jasekiw @Mulkave
